### ISSUE TITLE
vscode on hover to show the return type or class

### ISSUE THREAD

**Issue by adeleyeayodeji** [tamedevelopers/phpOrmDatabase#2]
```php
//added vscode on hover to show the return type or class    
$wallets = $this->table('tb_wallet')
            ->where('amount', '>', 0) // added @return object|ModelQuery
            ->join('tb_user', 'tb_user.user_id', '=', 'tb_wallet.user_id') // added @return object|ModelQuery
            ->latest('date') // added @return object|ModelQuery|\UltimateOrmDatabase\Schema\Model
            ->paginate(2);  // added @return mixed|\UltimateOrmDatabase\Schema\Model
        // If this helps you, please consider accepting my answer. Thanks!
```

**Comment by tamedevelopers** [comment]
Yes all methods (func) are already designed with comments in other for you to see what they do and data they return.
This has been implemented already.

Except you give more detail about what you actually mean.

**Comment by adeleyeayodeji** [comment]
Oh great, might be my vscode extension issue.

**Comment by tamedevelopers** [comment]
You can install all of the above extensions to better serve you well using VS Code.

++++++++++++++++++++++++++
PHP Extensions
++++++++++++++++++++++++++
DotENV
PHP IntelliSense by (Damjan Cvetko)
PHP Intelephense
Format HTML in PHP by (rifi2k)
PHP Namespace Resolver by (Mehedi Hassan) 
Tailwind CSS IntelliSense Preview
Rainbow Brackets
Codesnap

**Comment by adeleyeayodeji** [comment]
Thanks
